version: "3.7"
services:
  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
      target: build-stage
    container_name: app
    working_dir: /app
    volumes:
      - ./app:/app:delegated
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
